
-- Add missing columns to produto
ALTER TABLE public.produto
  ADD COLUMN IF NOT EXISTS image_url text,
  ADD COLUMN IF NOT EXISTS stock integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS colors text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS sizes text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS description text;

-- Add missing columns to usuarios (customers)
ALTER TABLE public.usuarios
  ADD COLUMN IF NOT EXISTS tags text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS last_interaction timestamptz DEFAULT now(),
  ADD COLUMN IF NOT EXISTS total_orders integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS endereco text;

-- Add missing columns to pedidos (orders)
ALTER TABLE public.pedidos
  ADD COLUMN IF NOT EXISTS customer_name text,
  ADD COLUMN IF NOT EXISTS customer_phone text,
  ADD COLUMN IF NOT EXISTS customer_address text,
  ADD COLUMN IF NOT EXISTS product_name text,
  ADD COLUMN IF NOT EXISTS product_image_url text,
  ADD COLUMN IF NOT EXISTS price numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS quantity integer DEFAULT 1,
  ADD COLUMN IF NOT EXISTS entregador text,
  ADD COLUMN IF NOT EXISTS pagamento_status text DEFAULT 'pendente',
  ADD COLUMN IF NOT EXISTS status_entrega text DEFAULT 'pendente',
  ADD COLUMN IF NOT EXISTS observacoes_entrega text,
  ADD COLUMN IF NOT EXISTS comprovativo_pagamento text,
  ADD COLUMN IF NOT EXISTS data_entrega timestamptz,
  ADD COLUMN IF NOT EXISTS humano_notificar boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS atendido_por text,
  ADD COLUMN IF NOT EXISTS controle_conversa text DEFAULT 'bot',
  ADD COLUMN IF NOT EXISTS status_alerta text DEFAULT 'pendente';

-- Create leads table
CREATE TABLE IF NOT EXISTS public.leads (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  phone text,
  email text,
  source text DEFAULT 'other',
  interest text,
  tags text[] DEFAULT '{}',
  first_interaction timestamptz DEFAULT now(),
  notes text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Create messages table
CREATE TABLE IF NOT EXISTS public.messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id bigint REFERENCES public.usuarios(id) ON DELETE CASCADE,
  customer_name text,
  text text NOT NULL,
  direction text NOT NULL CHECK (direction IN ('in', 'out')),
  timestamp timestamptz NOT NULL DEFAULT now(),
  is_bot boolean DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Create bot_learning table
CREATE TABLE IF NOT EXISTS public.bot_learning (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pergunta_cliente text NOT NULL,
  resposta_humana text,
  aprovada boolean DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Create unresolved_bot_messages table
CREATE TABLE IF NOT EXISTS public.unresolved_bot_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id bigint REFERENCES public.usuarios(id) ON DELETE CASCADE,
  customer_name text,
  mensagem text NOT NULL,
  resolved boolean DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Create store_config table
CREATE TABLE IF NOT EXISTS public.store_config (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_loja text,
  telefone text,
  endereco text,
  formas_pagamento text[] DEFAULT '{}',
  zonas_entrega text[] DEFAULT '{}',
  mensagem_boas_vindas text,
  linguagem_bot text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- RLS policies: allow public read for now (adjust later with auth)
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bot_learning ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.unresolved_bot_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.store_config ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read on leads" ON public.leads FOR SELECT USING (true);
CREATE POLICY "Allow public insert on leads" ON public.leads FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update on leads" ON public.leads FOR UPDATE USING (true);

CREATE POLICY "Allow public read on messages" ON public.messages FOR SELECT USING (true);
CREATE POLICY "Allow public insert on messages" ON public.messages FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public read on bot_learning" ON public.bot_learning FOR SELECT USING (true);
CREATE POLICY "Allow public insert on bot_learning" ON public.bot_learning FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update on bot_learning" ON public.bot_learning FOR UPDATE USING (true);

CREATE POLICY "Allow public read on unresolved_bot_messages" ON public.unresolved_bot_messages FOR SELECT USING (true);
CREATE POLICY "Allow public insert on unresolved_bot_messages" ON public.unresolved_bot_messages FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update on unresolved_bot_messages" ON public.unresolved_bot_messages FOR UPDATE USING (true);

CREATE POLICY "Allow public read on store_config" ON public.store_config FOR SELECT USING (true);
CREATE POLICY "Allow public insert on store_config" ON public.store_config FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update on store_config" ON public.store_config FOR UPDATE USING (true);

-- Also add RLS policies for existing tables
CREATE POLICY "Allow public read on produto" ON public.produto FOR SELECT USING (true);
CREATE POLICY "Allow public all on produto" ON public.produto FOR ALL USING (true);

CREATE POLICY "Allow public read on pedidos" ON public.pedidos FOR SELECT USING (true);
CREATE POLICY "Allow public all on pedidos" ON public.pedidos FOR ALL USING (true);

CREATE POLICY "Allow public read on usuarios" ON public.usuarios FOR SELECT USING (true);
CREATE POLICY "Allow public all on usuarios" ON public.usuarios FOR ALL USING (true);
